# ============================================================================
# PDF Chat Application Docker Compose - 前後端分離版本
# ============================================================================

version: "3.8"

services:
  # 後端 API 服務
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pdf-chat-backend
    ports:
      - "5009:5009"
    volumes:
      - pdf_uploads:/app/uploads
      - pdf_logs:/app/logs
      - ./backend/config.ini:/app/config.ini:ro
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5009/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 15s
    networks:
      - pdf-chat-network

  # 前端服務
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: pdf-chat-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - pdf-chat-network
    profiles:
      - prod

  # 開發環境前端服務 (可選)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: pdf-chat-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:5009/api
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pdf-chat-network
    profiles:
      - dev

volumes:
  pdf_uploads:
  pdf_logs:
    driver: local

networks:
  pdf-chat-network:
    driver: bridge
